### ISSUE TITLE
VM freezes after 'Booting' in Firefox with the HTTPS Everywhere extension enabled

### ISSUE THREAD

**Issue by aereaux** [cs-education/sysbuild#111]
In Firefox, with the HTTPS Everywhere extension enabled, the Virtual Machine gets stuck after printing out the 'Booting' message and then the line of equal signs.  When the extension is disabled, it proceeds without problem.  There are a couple of entries in the Javascript console which seem to indicate the problem:

    23:20:45.589 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cs-education.github.io/sysassets/sys.min.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>
    23:20:45.612 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cs-education.github.io/sysassets/sys.min.json. (Reason: CORS request failed).1 <unknown>
    ...
    23:20:47.305 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cs-education.github.io/sysassets/jor1kfs/sysroot/fs.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>
    23:20:47.306 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cs-education.github.io/sysassets/jor1kfs/sysroot/fs.json. (Reason: CORS request failed).1 <unknown>
    ...
     23:20:47.306 "Error at https://cs-education.github.io/jor1k/bin/jor1k-worker-min.js:9570: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"1 a1ebcd5e.main.js:2:5328

**Comment by neelabhg** [comment]
Hi, thanks for reporting the issue! I was able reproduce it. Below I'll explain the problem in more depth and suggest possible solutions for anyone working on the project. For now, you can use the temporary fix mentioned below.

#### Issue
When navigating to "https://cs-education.github.io/sys/" (notice the https) on Chrome (Version 45.0.2454.85 m), I get the following error (among others), with or without the [HTTPS Everywhere](https://www.eff.org/HTTPS-everywhere) extension enabled:
> Mixed Content: The page at 'https://cs-education.github.io/sys/#playground' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cs-education.github.io/sysassets/sys.min.json'. This request has been blocked; the content must be served over HTTPS.

When navigating to "https://cs-education.github.io/sys/" (notice the https) on Firefox (version 40.0.2), I get the following error (among others), without the HTTPS Everywhere extension (although this will most likely happen with the extension installed and enabled as well):
> Blocked loading mixed active content "http://cs-education.github.io/sysassets/sys.min.json" [[Learn More]](https://developer.mozilla.org/en-US/docs/Security/MixedContent)

The [MDN documentation on Mixed Content](https://developer.mozilla.org/en-US/docs/Security/MixedContent) (pointed to by the "Learn More" link) states that "Starting in Firefox 23, mixed active content is blocked by default".

Without the HTTPS Everywhere extension, when navigating to "http://cs-education.github.io/sys/" (notice the http, not https), the application works fine on both Chrome and Firefox.

#### Cause
[According to MDN](https://developer.mozilla.org/en-US/docs/Security/MixedContent), if an HTTPS page includes content retrieved through regular, cleartext HTTP, it is called a mixed content page.

We always use http when making AJAX requests (see, for example, [router.js#L30](https://github.com/cs-education/sysbuild/blob/master/app/scripts/router.js#L30)). Navigating to the web page using https, therefore, causes the page to become a mixed content page.

The HTTPS Everywhere extension makes this situation worse because by default it forces the browser to use https when loading GitHub Pages sites, even when the user types in the URL starting with "http://".

#### Possible solutions
* Dynamically build the URL and choose the protocol through which the page is loaded, perhaps using `window.location.protocol`
* Use [Protocol-relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/)
* Always use https (recommended by the article on Protocol-relative URLs linked in the point above)

#### Temporary fix
First, disable the HTTPS Everywhere extension, or navigate to http://cs-education.github.io/sys/ and uncheck the rule to force encrypted connections to GitHub Pages:

![image](https://cloud.githubusercontent.com/assets/846827/9830313/f1eb1822-58ee-11e5-9f58-da9928e75f00.png)

And then access the website using http: http://cs-education.github.io/sys/.

**Comment by neelabhg** [comment]
The application now works correctly with the HTTPS Everywhere extension enabled.
Check out the [staging link](https://cs-education.github.io/sys-staging/).
