### ISSUE TITLE
Create own disk image

### ISSUE THREAD

**Issue by angrave** [cs-education/sysbuild#3]
Currently using a modified version of hdgcc from jor1k. Would be great if we can create own custom disk image from scratch.

**Comment by neelabhg** [comment]
jor1k's filesystem management is now much better. After PR #101, we now serve a base filesystem provided by jor1k, and an extended filesystem from sysassets. So we have much more control over the files loaded by the VM. Files like `inittab` are stored in the git repository, and instead of using one big binary disk image, we have a build script combining package archives to form the filesystem (the contents of which are also in the git repository). So we know exactly what's being included as well as use version control features.

See the pull request for more details.
