### ISSUE TITLE
User interface doesn't return to 2-panel state after browser width change

### ISSUE THREAD

**Issue by scowalt** [cs-education/sysbuild#76]
Steps to reproduce:
  1. Load playground in standard wide-screen browser window
  2. Resize browser window to be very thin (~200 px wide)
  3. Expand browser window back to its original size

Expected behavior:
  - Interface returns to the state it was in before step 1

Actual behavior:
  - Virtual machine panel no longer displays, editor takes up full page width. No obvious way to return interface to previous state besides refresh.

**Comment by neelabhg** [comment]
This happens because when the window size is small, the VM pane collapses. When resized back to original size, the VM pane still remains collapsed - it should ideally expand again. It can be reopened by clicking the small handle at the left boundary of the pane, although this should happen automatically and the handle is not prominent enough to be obvious for the user.

We use [jQuery UI Layout](http://layout.jquery-dev.com/) to divide the UI into panes.

**Comment by wchill** [comment]
A simple way to fix this might be to just programmatically 'click' the handle upon resize. From a brief skim/Ctrl+F, I don't see any relevant options in the UI Layout documentation that would be of any help, but there may be a way that I overlooked.
